version: '3'
networks:
  consul_net:
services:
  consul1:
    image: consul:latest
    container_name: consul1
    restart: always
    networks:
     - consul_net
    command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=consul1 
  consul2:
    image: consul:latest
    container_name: consul2
    networks:
     - consul_net
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul2
  consul3:
    image: consul:latest
    container_name: consul3
    networks:
     - consul_net
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul3
  consul4:
    image: consul:latest
    container_name: consul4
    networks:
     - consul_net
    restart: always
    ports:
      - 8500:8500
    command: agent -client=0.0.0.0 -retry-join=consul1 -ui -node=client1